_wandb:
    value:
        cli_version: 0.22.3
        e:
            wxirokpbhn1p7g6qsg6gw4ucjc22t06w:
                codePath: /home/teo/kaggle/csiro/train.ipynb
                codePathLocal: train.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "123253538816"
                        used: "106410668032"
                email: butnaruteodor@gmail.com
                executable: /home/teo/kaggle/csiro/.venv/bin/python
                git:
                    commit: b8bb13ee03e96137397601e99e63088c4a6238ab
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-344af833-a091-895e-3322-db62bb3127ef
                host: teo-HP-Pavilion-Gaming-Laptop-15-dk2xxx
                memory:
                    total: "16499208192"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /home/teo/kaggle/csiro/train.ipynb
                python: CPython 3.10.18
                root: /home/teo/kaggle/csiro
                startedAt: "2025-11-06T17:04:48.820442Z"
                writerId: wxirokpbhn1p7g6qsg6gw4ucjc22t06w
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 80
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 80
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.18
            "5": 0.22.3
            "8":
                - 1
                - 2
            "10":
                - 20
            "12": 0.22.3
            "13": linux-x86_64
ALL_TARGET_COLS:
    value:
        - Dry_Green_g
        - Dry_Dead_g
        - Dry_Clover_g
        - GDM_g
        - Dry_Total_g
BASE_PATH:
    value: csiro-biomass
BATCH_SIZE:
    value: 2
CAT_AUX_COLS:
    value:
        - State_idx
        - Species_idx
CONT_AUX_COLS:
    value:
        - Pre_GSHH_NDVI
        - Height_Ave_cm
        - day_sin
        - day_cos
DERIVED_COLS:
    value:
        - Dry_Clover_g
        - Dry_Dead_g
DETERMINISTIC:
    value: true
DEVICE:
    value: cuda
EPOCHS:
    value: 15
FREEZE_BACKBONE:
    value: false
GRAD_ACC:
    value: 4
IMG_SIZE:
    value: 512
LR:
    value: 0.0001
MODEL_DIR:
    value: out
MODEL_NAME:
    value: convnextv2_atto
N_FOLDS:
    value: 5
N_SPECIES:
    value: 15
N_STATES:
    value: 4
NUM_WORKERS:
    value: 1
PATIENCE:
    value: 5
PRETRAINED:
    value: true
R2_WEIGHTS:
    value:
        - 0.1
        - 0.1
        - 0.1
        - 0.2
        - 0.5
SEED:
    value: 122
TARGET_COLS:
    value:
        - Dry_Total_g
        - GDM_g
        - Dry_Green_g
TRAIN_CSV:
    value: csiro-biomass/train.csv
TRAIN_IMAGE_DIR:
    value: csiro-biomass/train
W_CONT:
    value: 0.5
W_SPECIES:
    value: 0.25
W_STATE:
    value: 0.25
WD:
    value: 0.01
